# This is a basic workflow to help you get started with Actions

name: Build_susfs_ksu_kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
         with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
       - name: Checkout Repo
         uses: actions/checkout@v4
      
      #Install Repo
       - name: Install Repo
         run: sudo apt install repo

      #Install zip
       - name: Install zip
         run: sudo apt install zip

      #Install curl
       - name: Install curl
         run: sudo apt install curl

      #Install sed
       - name: Install sed
         run: sudo apt install sed

      # Runs Kernel Build Script
       - name: Run Build Script
         run: sudo bash ./buildksususfs.sh

